# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d94482721bcf6dc44fe92b0420bcea8e3e0183e14c5936cc26d1de67b731ab0c00c52902e474920ffa1b94d5a83716820328977262482671442d99160cb04e

test:
  secret_key_base: 5eab5404e5f47e763d95e68798eccdabe77e14f85855dc4f6decf818f655c73768bd79d7c078ce943e9985d0904b40d650b2b2e41e10dd0cc9b316e917e7df0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
